# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'textFieldTask' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for textFieldTask

  target 'textFieldTaskTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'textFieldTaskUITests' do
    # Pods for testing
  end

pod 'IQKeyboardManagerSwift'

end
